In [3]:
# import the dependencies
from load_ardis_mnist import load_ardis_mnist
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [13]:
# load the data
(train_images, y_train), (test_images,
                               y_test) = load_ardis_mnist()

In [14]:
# flatten the image into an array
train_images = train_images.reshape((-1, 784))
test_images = test_images.reshape((-1, 784))

In [16]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(train_images)
X_test = sc_X.transform(test_images)

In [30]:
classifier = KNeighborsClassifier(n_neighbors=5, p=2,metric='euclidean')
# Fit Model
classifier.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean')

In [31]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 0, 6, ..., 4, 5, 6])

In [32]:
print(accuracy_score(y_test, y_pred))

0.9265454545454546


In [118]:
cm = confusion_matrix(y_test, y_pred)
print (cm)

[[1052    3    1    2    1    2   12    5    0    2]
 [   0 1222    3    0    1    1    4    3    0    1]
 [  15   16 1034   13    7    1    6   13   17   10]
 [   9   12   13 1022    3   19    3   12   13    4]
 [   2   13    6    2 1003    5   10   10    3   28]
 [  10    4    5   16   10  902   16    7    6   16]
 [  22   14    5    2    3    3 1002    0    3    4]
 [   0   34   14    6   12    7    1 1021    2   31]
 [  15    9   10   28    8   28    6   12  936   22]
 [  10   18    9   10   20    5    1   34    4  998]]


In [119]:
import cv2
img = cv2.imread("9.png")

In [120]:
img_grey = cv2.cvtColor(img, cv2. COLOR_BGR2GRAY)
img_res = cv2.resize(img_grey, dsize=(28, 28), interpolation=cv2.INTER_AREA)

In [121]:
img_res = (img_res/255) 

In [122]:
img_res = img_res.reshape((-1, 784))

In [123]:
img_predict = classifier.predict(img_res)
print("Model prediction",img_predict)

Model prediction [9]
